import Navbar from './navbar'
import Footer from './footer'
import Head from 'next/head'
import { Poppins,Lora } from 'next/font/google'
export default function Layout({ children }) {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Lora:wght@500;700&family=Poppins:wght@200;300;400&display=swap" rel="stylesheet"/>
      </Head>
      <Navbar />
      <main>{children}</main>
      <Footer />
    </>
  )
}